
name: 'AAAAAAAA'


on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'target environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - stage
          - qa
jobs:
  run-shell-commands:
    runs-on: self-hosted
    steps: 
      - name: single command 
        run: echo "Hello World"



