name: shell commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps: 
      - name: single command 
        run: echo "Hello World"
      - name: multi-line
        run: |
          node -v
          npm -v
      - name: runs-on-self-hosted
        run: echo "Run this script !!!!!"

  run-shell-commands-2:
    runs-on: ubuntu-latest
    needs: run-shell-commands
    steps: 
      - name: list files
        uses: actions/checkout@v3
        



